"use client";

import { useState } from "react";
import { ShieldCheck, ChevronDown } from "lucide-react";

export function PrivacyStatement() {
  const [open, setOpen] = useState(false);

  return (
    <div className="mt-4 border-t border-border/40 pt-3">
      {/* Trigger */}
      <button
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex items-center gap-1.5 text-muted-foreground transition-colors hover:text-foreground"
      >
        <ShieldCheck className="h-3.5 w-3.5 shrink-0" />
        <span className="text-[12px]">Privacy Statement</span>
        <ChevronDown
          className="h-3 w-3 shrink-0 transition-transform duration-200"
          style={{ transform: open ? "rotate(180deg)" : "rotate(0deg)" }}
        />
      </button>

      {/* Expanded content */}
      {open && (
        <div className="mt-6 max-w-3xl space-y-6 pb-6 text-[13px] leading-relaxed text-foreground/75">

          {/* ── Demo warning box ── */}
          <div className="rounded-lg border-2 border-orange-400 bg-orange-50 px-4 py-3.5 dark:border-orange-600 dark:bg-orange-950/30">
            <p className="text-[12px] font-bold uppercase tracking-wider text-orange-700 dark:text-orange-400">
              Test Service
            </p>
            <p className="mt-1.5 text-[13px] text-orange-900 dark:text-orange-300">
              PROLOG is currently a test application. You should not enter, speak, or upload any
              real patient data, sensitive clinical information, or data about real individuals.
              Do not use this service in a live clinical setting or with any actual patient details.
            </p>
          </div>

          <div className="flex items-baseline justify-between">
            <h2 className="text-[15px] font-semibold text-foreground">Privacy Statement</h2>
            <span className="text-[11px] text-muted-foreground">Last updated: April 2026</span>
          </div>

          {/* 1 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">1. About Us</h3>
            <p>
              PROLOG is a voice-based clinical communication training simulator built for NHS Scotland
              and HSCP staff. This notice explains how we collect, use, and protect your personal
              information when you use the service. For any privacy-related queries, please contact
              us using the details on our website.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">2. What Personal Information We Collect</h3>
            <p className="mb-2">When you use PROLOG, we may collect and process the following information:</p>
            <ul className="space-y-1.5 pl-3">
              {[
                ["Account information", "Your name, email address, and role (trainee, educator, or administrator) when you register."],
                ["Voice and audio data", "Audio recordings of your voice during simulation sessions, transmitted to third-party providers for real-time processing. Sessions may be recorded and stored for post-session review."],
                ["Conversation transcripts", "A written record of your spoken utterances and the AI patient's responses during each session, generated by automated transcription."],
                ["Session performance data", "Escalation levels, classifier outputs, scores, and event logs generated during and after each simulation session."],
                ["Scenario content", "Patient profiles, personality traits, clinical context, and rules authored by educators when creating training scenarios."],
                ["Reflection and feedback data", "Trainee self-reflections and educator notes attached to completed sessions."],
                ["Technical and diagnostic data", "Browser type, device information, usage data, and error reports collected automatically to maintain service reliability."],
              ].map(([label, desc]) => (
                <li key={label} className="flex gap-2">
                  <span className="mt-0.5 shrink-0 text-muted-foreground">•</span>
                  <span><span className="font-medium text-foreground">{label}:</span> {desc}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* 3 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">3. How We Use Your Information</h3>
            <p className="mb-2">We use your personal information to:</p>
            <ul className="space-y-1 pl-3">
              {[
                "Provide the AI-driven voice simulation and de-escalation training service.",
                "Process your voice in real time to generate AI patient responses and automated transcription.",
                "Classify your utterances to assess communication technique and generate escalation state changes.",
                "Generate performance scores and qualitative feedback after each session.",
                "Enable session review, reflection, and educator feedback workflows.",
                "Store session recordings for post-session review where applicable.",
                "Monitor errors and diagnose issues to maintain service reliability.",
                "Improve and maintain the service.",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="mt-0.5 shrink-0 text-muted-foreground">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">4. Legal Basis for Processing</h3>
            <p className="mb-2">We process your personal information on the following bases:</p>
            <ul className="space-y-1 pl-3">
              {[
                ["Contract", "Processing necessary to provide the service you have requested."],
                ["Legitimate interests", "To maintain and improve the service, and to ensure its security."],
                ["Consent", "Where you have given explicit consent, for example when recording a session that captures your voice."],
              ].map(([label, desc]) => (
                <li key={label} className="flex gap-2">
                  <span className="mt-0.5 shrink-0 text-muted-foreground">•</span>
                  <span><span className="font-medium text-foreground">{label}:</span> {desc}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">5. Your Voice and Session Data</h3>
            <p>
              Your voice is transmitted to OpenAI&apos;s Realtime API during simulation sessions for the
              purpose of generating AI patient responses and automated transcription. Session audio
              may be recorded and stored for review. You are responsible for ensuring that no real
              patient data or sensitive clinical information is spoken or described during simulation
              sessions.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h3 className="mb-2 text-[13.5px] font-semibold text-foreground">6. Third-Party Service Providers</h3>
            <p className="mb-3">
              We do not sell your personal information. To deliver the service, we use the following
              third-party providers who may process your data on our behalf:
            </p>
            <div className="space-y-2.5">
              {[
                {
                  name: "Supabase",
                  role: "database, authentication, and file storage",
                  desc: "Stores application data including user accounts, scenario content, session transcripts, reflections, educator notes, and session audio recordings. Also provides user authentication.",
                },
                {
                  name: "OpenAI",
                  role: "AI voice, transcription, and classification",
                  desc: "Processes simulation text and audio sent by the app to power real-time voice conversation, transcription, communication-technique classification, voice-profile generation, the AI clinician bot, and text-to-speech.",
                },
                {
                  name: "Vercel",
                  role: "frontend and API hosting",
                  desc: "Hosts the web application and server-side route handlers that serve the frontend and API.",
                },
              ].map(({ name, role, desc }) => (
                <div key={name} className="rounded-lg border border-border/60 bg-card px-3.5 py-3">
                  <span className="font-semibold text-foreground">{name}</span>
                  <span className="ml-1.5 text-[12px] text-muted-foreground">({role})</span>
                  {" — "}
                  {desc}
                </div>
              ))}
            </div>
            <p className="mt-3 text-[12px] text-muted-foreground">
              Each provider has its own privacy, security, and compliance documentation. The deploying
              organisation should review those current terms and any signed supplier agreements separately.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">7. International Data Transfers</h3>
            <p>
              Some third-party providers operate internationally. Depending on how the service is
              deployed and configured, personal information may be processed outside the United Kingdom.
              Cross-border transfer safeguards should be documented in the deploying organisation&apos;s
              supplier agreements and operational privacy documentation.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">8. Data Retention</h3>
            <p>
              We retain personal information only for as long as needed to operate the service,
              support review workflows, and meet applicable organisational or legal requirements.
              Exact retention periods for transcripts, reflections, notes, and audio recordings
              should be defined by the deploying organisation&apos;s operational policy.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">9. How We Protect Your Information</h3>
            <p className="mb-2">We take appropriate technical and organisational measures to protect your personal information, including:</p>
            <ul className="space-y-1 pl-3">
              {[
                "Encryption of data in transit and, where supported by the configured providers, at rest.",
                "Access controls limiting who can view your data.",
                "Error monitoring and logging to detect and respond to incidents.",
                "Regular review of service configuration and third-party provider documentation.",
                "Controlled use of authenticated routes and server-side secrets for privileged operations.",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="mt-0.5 shrink-0 text-muted-foreground">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* 10 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">10. Cookies</h3>
            <p>
              We use essential cookies required for the site to operate, including session management
              and authentication state. You can control cookie preferences through your browser settings.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">11. Your Rights</h3>
            <p className="mb-2">Under data protection law, you have the right to:</p>
            <ul className="space-y-1 pl-3">
              {[
                "Access the personal information we hold about you.",
                "Rectify inaccurate or incomplete information.",
                "Erase your personal information where there is no compelling reason for continued processing.",
                "Object to processing of your personal information.",
                "Data portability — receive your data in a structured, commonly used format.",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="mt-0.5 shrink-0 text-muted-foreground">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mt-2">To exercise any of these rights, please contact us using the details on our website.</p>
          </section>

          {/* 12 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">12. Complaints</h3>
            <p>
              If you are unhappy with how we handle your personal information, you have the right to
              raise a concern with the Information Commissioner&apos;s Office (ICO) at{" "}
              <a
                href="https://ico.org.uk"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:text-foreground"
              >
                ico.org.uk
              </a>.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h3 className="mb-1.5 text-[13.5px] font-semibold text-foreground">13. Updates</h3>
            <p>
              We may update this privacy statement from time to time. Any changes will be posted on
              this page. We encourage you to review it periodically.
            </p>
          </section>

        </div>
      )}
    </div>
  );
}
